### PR TITLE
update the blake3 dependency to v1.2

### PR DESCRIPTION
**Pull request by oconnor663**
The blake3 crate currently has a MSRV of 1.51 for const generics.

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Don't think we have an MSRV guarantee so yeah, sure. Any particular reason for this?

**Comment by nabijaczleweli** [comment]
Merged as e40bf4ea0c84905d54fc6619f78935b56ca234dc.

**Comment by oconnor663** [comment]
Thanks!

> Any particular reason for this?

Today's 1.2.0 release included a security fix, so I took a look at some of the callers on crates.io who were still on the 0.3.x series.

**Comment by nabijaczleweli** [comment]
Oh, cool! Released in [`v0.9.1`](https://github.com/nabijaczleweli/checksums/releases/tag/v0.9.1).

**Pull request closed without merging**
